version: '3.4'

services:
  koel:
    image: walkingcrows/rpi-koel:3.7.0
    depends_on:
      - database
    ports:
      - 8888:80
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_USERNAME: koel
      DB_PASSWORD: koel
      DB_DATABASE: koel
      ADMIN_EMAIL:    someone@example.test
      ADMIN_NAME:     admin
      ADMIN_PASSWORD: admin
    volumes:
      - ./config:/config
      - /mnt/NAS/NAS/Audio/:/media:
      
  database:
    image: hypriot/rpi-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: koel
      MYSQL_USER: koel
      MYSQL_PASSWORD: koel
